# Generated by Django 4.1.5 on 2023-02-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='price',
        ),
    ]
