# Generated by Django 4.1.5 on 2023-02-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_purchase_price_remove_sales_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='dop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
