# Generated by Django 4.1.5 on 2023-02-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_purchase_dop_alter_purchase_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
