# Generated by Django 4.1.5 on 2023-02-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='gst_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
