# Generated by Django 4.1.5 on 2023-02-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_buyer_gst_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='status',
        ),
        migrations.AddField(
            model_name='purchase',
            name='avg_buy_price',
            field=models.FloatField(null=True),
        ),
    ]
