# Generated by Django 4.1.5 on 2023-02-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_purchase_dop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='avg_price',
            new_name='avg_buy_price',
        ),
    ]
