# Generated by Django 4.1.5 on 2023-02-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_sales_dos_alter_sales_qty_alter_sales_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='gst_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
