# Generated by Django 4.1.5 on 2023-03-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_buyer_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='Status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed')], default='pending', max_length=100),
        ),
    ]
