# Generated by Django 4.1.5 on 2023-03-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_sales_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='updatedby',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Status',
            field=models.CharField(choices=[('pending', 'pending'), ('Dispatch ', 'Dispatch')], default='pending', max_length=100),
        ),
    ]
